services:
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_POLL_INTERVAL=60 #poll every 60 seconds
      - TZ=Europe/Berlin
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  production:
    image: ghcr.io/inab/bench_event_api:${BENCH_EVENT_API_TAG:-latest}
    build:
      context: .
    ports:
      - '${PROD_PORT:-5000}:5000'
    volumes:
      - ./flask_app.py.json.prod:/usr/src/app/flask_app.py.json:ro
      - ./flask_app.py.json.prod.auth:/usr/src/app/flask_app.py.json.auth:ro
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  
  # This one is only used for development and local testing purposes
  nginx_production:
    image: docker.io/library/nginx:1.27
    profiles:
      - nginx
    depends_on:
      - production
    ports:
      - '8080:80'
    volumes:
      - ./conf/nginx.default.conf:/etc/nginx/conf.d/default.conf:ro

  preprod:
    image: ghcr.io/inab/bench_event_api:${BENCH_EVENT_API_TAG:-latest}
    build:
      context: .
    ports:
      - '${PREPROD_PORT:-5001}:5000'
    volumes:
      - ./flask_app.py.json.preprod:/usr/src/app/flask_app.py.json:ro
      - ./flask_app.py.json.preprod.auth:/usr/src/app/flask_app.py.json.auth:ro
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  test1:
    image: ghcr.io/inab/bench_event_api:${BENCH_EVENT_API_TAG:-latest}
    build:
      context: .
    ports:
      - '${TEST1_PORT:-5002}:5000'
    volumes:
      - ./flask_app.py.json.test1:/usr/src/app/flask_app.py.json:ro
      - ./flask_app.py.json.test1.auth:/usr/src/app/flask_app.py.json.auth:ro
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  test2:
    image: ghcr.io/inab/bench_event_api:${BENCH_EVENT_API_TAG:-latest}
    build:
      context: .
    ports:
      - '${TEST2_PORT:-5003}:5000'
    volumes:
      - ./flask_app.py.json.test2:/usr/src/app/flask_app.py.json:ro
      - ./flask_app.py.json.test2.auth:/usr/src/app/flask_app.py.json.auth:ro
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: ${MTU:-1500}
